config/routes.rb
GongApp::Application.routes.draw do

  resources :gongs do
    delete 'votes', to: 'gongs#reset_votes', on: :member, as: :reset_votes
    resources :votes
  end

  root "gongs#new"
end

app/models/gong.rb
class Gong < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :votes

  before_create :set_name
  validates_uniqueness_of :name

  def can_vote?(session_id)
    self.votes.where(session_id: session_id).count == 0
  end

  def set_name
    self.name ||= self.generate_unique_name
  end

  def generate_unique_name
    potential_name = (0...5).map { (65 + rand(26)).chr }.join
    if Gong.where(name: potential_name).count > 0
      self.generate_unique_name
    else
      potential_name
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :gong

  validates_presence_of :session_id
  validate :is_unique_for_user

  def is_unique_for_user
    if Vote.where(gong_id: self.gong_id, session_id: self.session_id).count > 0
      errors[:base] << "You have already voted on this."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/gongs_controller.rb
class GongsController < ApplicationController
  before_action :set_gong, only: [:show, :edit, :update, :destroy, :reset_votes]

  # GET /gongs
  # GET /gongs.json
  def index
    @gongs = Gong.all
  end

  # GET /gongs/1
  # GET /gongs/1.json
  def show
  end

  # GET /gongs/new
  def new
    @gong = Gong.new
  end

  # GET /gongs/1/edit
  def edit
  end

  # POST /gongs
  # POST /gongs.json
  def create
    @gong = Gong.new(gong_params)

    respond_to do |format|
      if @gong.save
        format.html { redirect_to @gong, notice: 'Gong was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gong }
      else
        format.html { render action: 'new' }
        format.json { render json: @gong.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gongs/1
  # PATCH/PUT /gongs/1.json
  def update
    respond_to do |format|
      if @gong.update(gong_params)
        format.html { redirect_to @gong, notice: 'Gong was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gong.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gongs/1
  # DELETE /gongs/1.json
  def destroy
    @gong.destroy
    respond_to do |format|
      format.html { redirect_to gongs_url }
      format.json { head :no_content }
    end
  end

  def reset_votes
    @gong.votes.destroy_all
    respond_to do |format|
      format.html { redirect_to gong_url(@gong) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gong
      @gong = Gong.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gong_params
      params.require(:gong).permit(:name, :threshhold)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_gong
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to [@gong, @vote], notice: 'Vote was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@gong, @vote] }
      else
        format.html { render action: 'new' }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url }
      format.json { head :no_content }
    end
  end

  private
    def set_vote
      @vote = Vote.find(params[:id])
    end

    def set_gong
      @gong = Gong.friendly.find(params[:gong_id])
    end

    def vote_params
      params.require(:gong_id)
      {session_id: view_context.current_user, gong_id: @gong.id}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    request.session_options[:id]
  end
end

app/helpers/gongs_helper.rb
module GongsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/gongs/_form.html.haml
= form_for @gong do |f|
  - if @gong.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gong.errors.count, "error")} prohibited this gong from being saved:"
      %ul
        - @gong.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :threshhold
    = f.number_field :threshhold
  .actions
    = f.submit 'Save'

app/views/gongs/edit.html.haml
%h1 Editing gong

= render 'form'

= link_to 'Show', @gong
\|
= link_to 'Back', gongs_path

app/views/gongs/index.html.haml
%h1 Listing gongs

%table
  %tr
    %th Name
    %th Threshhold
    %th
    %th
    %th

  - @gongs.each do |gong|
    %tr
      %td= gong.name
      %td= gong.threshhold
      %td= link_to 'Show', gong
      %td= link_to 'Edit', edit_gong_path(gong)
      %td= link_to 'Destroy', gong, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Gong', new_gong_path

app/views/gongs/new.html.haml
%h1 New gong

= render 'form'

= link_to 'Back', gongs_path

app/views/gongs/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @gong.name
%p
  %b Threshhold:
  = @gong.threshhold
%p
  %b Votes:
  %span.vote_count= @gong.votes.count

= link_to 'Edit', edit_gong_path(@gong)
\|
= link_to 'Reset', reset_votes_gong_path(@gong), :method => :delete, :data => {:confirm => 'Are you sure?' }

- if @gong.can_vote?(current_user)
  %span.vote-wrapper
    \|
    = link_to 'Vote', gong_votes_path(@gong), class: :vote

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GongApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %> <%= controller.action_name %>">

<%= yield %>

</body>
</html>

app/views/votes/_form.html.haml
= form_for [@gong, @vote] do |f|
  - if @vote.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vote.errors.count, "error")} prohibited this vote from being saved:"
      %ul
        - @vote.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/votes/edit.html.haml
%h1 Editing vote

= render 'form'

= link_to 'Show', @vote
\|
= link_to 'Back', votes_path

app/views/votes/index.html.haml
%h1 Listing votes

%table
  %tr
    %th Gong
    %th Session
    %th
    %th
    %th

  - @votes.each do |vote|
    %tr
      %td= vote.gong_id
      %td= vote.session_id
      %td= link_to 'Show', [vote.gong, vote]
      %td= link_to 'Edit', edit_gong_vote_path(vote.gong, vote)
      %td= link_to 'Destroy', [vote.gong, vote], :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/votes/new.html.haml
%h1 New vote

= render 'form'

= link_to 'Back', gong_votes_path(@gong)

app/views/votes/show.html.haml
%p#notice= notice

%p
  %b Gong:
  = @vote.gong_id
%p
  %b Session:
  = @vote.session_id

= link_to 'Edit', edit_gong_vote_path(@vote.gong, @vote)